-- Seeded defaults: the same values a fresh Apps Script workspace got.
set search_path to hrms, public, extensions;

insert into settings (key, value) values
  ('company_name', 'My Company Pvt Ltd'),
  ('company_address', ''),
  ('currency', 'INR'),
  ('pf_employee_pct', '12'),
  ('pf_employer_pct', '13'),
  ('pf_wage_ceiling', '15000'),
  ('esi_employee_pct', '0.75'),
  ('esi_employer_pct', '3.25'),
  ('esi_wage_ceiling', '21000'),
  ('pt_amount', '200'),
  ('weekly_off', 'Sun'),
  ('shift_start', '09:30'),
  ('shift_end', '18:30'),
  ('grace_minutes', '15'),
  ('ot_after_minutes', '30'),
  ('full_day_hours', '8'),
  ('half_day_hours', '4'),
  ('saturday_policy', 'working'),
  ('default_shift', 'General'),
  ('late_marks_per_halfday', '3'),
  ('late_mark_slab', '6:1, 12:2, 24:3'),
  -- Payment of Bonus Act, as amended in 2015
  ('bonus_rate_pct', '8.33'),
  ('bonus_eligibility_ceiling', '21000'),
  ('bonus_calc_ceiling', '7000'),
  ('bonus_min_days', '30'),
  -- Payment of Gratuity Act
  ('gratuity_min_years', '1'),
  ('gratuity_prorata', 'no'),
  ('gratuity_days_per_year', '15'),
  ('gratuity_month_days', '26'),
  ('gratuity_ceiling', '2000000'),
  ('ot_pay_enabled', 'no'),
  ('ot_rate_multiplier', '1'),
  ('ot_max_hours_month', '60'),
  ('sandwich_rule', 'no'),
  ('excess_leave_unpaid', 'yes'),
  ('leave_after_days', '0'),
  ('payroll_basis', 'calendar'),
  ('payroll_rounding', '1'),
  ('essl_mode', 'none'),
  ('essl_api_url', ''),
  ('essl_api_user', ''),
  ('essl_auth_style', 'basic'),
  ('essl_device_serial', ''),
  ('essl_push_url', ''),
  ('essl_push_enabled', 'no'),
  ('sql_server', ''),
  ('sql_database', 'etimetracklite1'),
  ('sql_table', 'DeviceLogs'),
  ('sql_user', ''),
  ('sync_last_pull', ''),
  ('sync_last_push', ''),
  ('import_companies', ''),
  ('register_group_by', 'unit'),
  ('bootstrap_attendance_months', '2'),
  ('payslip_email_enabled', 'yes'),
  ('payslip_email_attach_pdf', 'yes'),
  ('payslip_email_subject', 'Payslip for {month} - {company}'),
  ('payslip_email_message', 'Dear {name},

Please find your payslip for {month} attached.
Net pay credited: {net}.

For any correction please write back to HR within 7 days.

Regards,
{company}'),
  ('payslip_email_from_name', ''),
  ('payslip_email_reply_to', ''),
  ('payslip_email_cc', ''),
  ('payslip_email_bcc', ''),
  ('web_punch_enabled', 'yes'),
  ('geofence_enabled', 'no'),
  ('geofence_mode', 'block'),
  ('geofence_accuracy_m', '120'),
  ('geofence_allow_od', 'yes'),
  ('punch_out_mandatory', 'yes'),
  ('co_payout_enabled', 'yes'),
  ('co_validity_days', '90'),
  ('register_footer', ''),
  ('keep_punch_log', 'yes'),
  ('punch_log_days', '90'),
  ('leave_types', 'Casual,Sick,Earned,Unpaid'),
  ('quota_casual', '12'),
  ('quota_sick', '6'),
  ('quota_earned', '15')
on conflict (key) do nothing;
